default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { "13306" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ez_split_development

test:
  <<: *default
  database: ez_split_test

production:
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "danangtokyo01" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { "3306" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: ez_split_production

